TRANSACTION_BUY = "BUY"
TRANSACTION_SELL = "SELL"

# CONFIG
DATE_COLUMN_KEY = "date_column"
DATE_FORMAT_KEY = "date_format"
TICKER_COLUMN_KEY = "ticker_column"
TICKER_TO_TRACK_KEY = "ticker_to_track"
QUANTITY_COLUMN_KEY = "quanitity_column"
SECURITY_PRICE_COLUMN_KEY = "security_price_column"
TRANSACTION_TYPE_KEY = "transaction_type_column"
TRANSACTION_BUY_VALUE = "transaction_buy_values"
TRANSACTION_SELL_VALUE = "transaction_sell_values"
LAST_DATE_KEY = "last_date"
LAST_PRICE_KEY = "last_price"
CAPTIAL_GAINS_TAX_RATE_KEY = "capital_gains_tax_rate"
INCOME_TAX_RATE_KEY = "income_tax_rate"
